import Head from "next/head";
import Image from "next/image";



import dea1 from "../assets/Dea Imeraj.jpg";
import dea2 from "../assets/Ferideja 2.jpg";
import terminal from "../assets/termonal.jpg";
import party from "../assets/party.jpg";
import azrendering from "../assets/azrendering.jpg";
import arameras from  "../assets/arameras.jpg";
import remix from  "../assets/remix.jpg";
import solatium from  "../assets/solatium.jpg";
import downloadIcon from "../assets/download-icon.svg";
import Link from "next/link";


export default function Home() {
  return (
    <div className="px-2 bg-[#0E0E0F] text-[#EAEAEA]">
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by Mike van Peeren" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <main className="overflow-hidden">
        <div className="flex header" id="box">
          <h1 className="text-[#EAEAEA] text-[296px] flex justify-center items-center">POrtfolio <span></span></h1>
          <h1 className="text-[#EAEAEA] text-[296px] flex justify-center items-center">POrtfolio <span></span></h1>
          <h1 className="text-[#EAEAEA] text-[296px] flex justify-center items-center">POrtfolio <span></span></h1>
          <h1 className="text-[#EAEAEA] text-[296px] flex justify-center items-center">POrtfolio <span></span></h1>
        </div>
        <div className="container">
          <div className="grid grid-cols-6">
            <div className="col-span-1">
              <Image src={dea1}/>
            </div>
            <div className="flex col-span-4 max-w-[938px] justify-center items-center mx-[60px]">
              <div><h2 className="text-[77px] text-right leading-tight">Dea Imeraj</h2></div>
              <div>
                <h3 className="text-[18px] leading-6 ml-[23px]">
                  Hello I’m Dea, a graphic designer and illustrator based in Tirana/Albania, currently working at Tok Digital Agency. My practice of graphic design is playful and didactic, attached to a meaning and good use of typography. My work is very varied, from branding, editorial, web design and also fun illustrations. 
                </h3>
            </div>
            </div>
            <div className="col-span-1 mt-9">
              <Image src={dea2}/>
            </div>
          </div>
        </div>
          <div className="blank-space">
            <div className="dot">
              <span></span>
            </div>
          </div>
          <div className="menu container flex text-[77px] items-center justify-center mt-28">
            <div className=""><span>work</span></div>
            <div className="ml-4"><span>about</span></div>
            <div className="ml-4"><span>contact</span></div>
          </div>
          <div className="container mt-[92px] uppercase">
            <div className="grid grid-cols-3">
              <div className="col-span-2"><Image src={terminal}/></div>
              <div className="flex-col flex justify-between ml-8">
                <div className="text-[22px]">
                  <div className="date">(2021)</div>
                  <div className="job-desc leading-none">Brand Identity <br/>Web Design</div>
                </div>
                <div className="pr-name text-[42px] leading-none">Private terminal & Exclusive Club </div>
              </div>
            </div>
          </div>
          <div className="container mt-[205px] uppercase">
            <div className="grid grid-cols-3">
              <div className="flex-col flex justify-between ml-8 text-right mr-8">
                <div className="text-[22px]">
                  <div className="date">(2021)</div>
                  <div className="job-desc leading-none">Brand Identity <br/>Web Design</div>
                </div>
                <div className="pr-name text-[42px] leading-none">The STreet Party</div>
              </div>
              <div className="col-span-2"><Image src={party}/></div>
            </div>
          </div>
          <div className="container mt-[205px] uppercase">
            <div className="grid grid-cols-3">
              <div className="col-span-2"><Image src={azrendering}/></div>
              <div className="flex-col flex justify-between ml-8">
                <div className="text-[22px]">
                  <div className="date">(2021)</div>
                  <div className="job-desc leading-none">Brand Identity <br/>Web Design</div>
                </div>
                <div className="pr-name text-[42px] leading-none">Az Rendering</div>
              </div>
            </div>
          </div>
          <div className="container mt-[205px] uppercase">
            <div className="grid grid-cols-3">
              <div className="flex-col flex justify-between ml-8 text-right mr-8">
                <div className="text-[22px]">
                  <div className="date">(2021)</div>
                  <div className="job-desc leading-none">Brand Identity <br/>Web Design</div>
                </div>
                <div className="pr-name text-[42px] leading-none">arameras</div>
              </div>
              <div className="col-span-2"><Image src={arameras}/></div>
            </div>
          </div>
          <div className="container mt-[205px] uppercase">
            <div className="grid grid-cols-3">
              <div className="col-span-2"><Image src={remix}/></div>
              <div className="flex-col flex justify-between ml-8">
                <div className="text-[22px]">
                  <div className="date">(2021)</div>
                  <div className="job-desc leading-none">Brand Identity <br/>Web Design</div>
                </div>
                <div className="pr-name text-[42px] leading-none">remix</div>
              </div>
            </div>
          </div>
          <div className="container mt-[205px] uppercase">
            <div className="grid grid-cols-3">
              <div className="flex-col flex justify-between ml-8 text-right mr-8">
                <div className="text-[22px]">
                  <div className="date">(2021)</div>
                  <div className="job-desc leading-none">Brand Identity <br/>Web Design</div>
                </div>
                <div className="pr-name text-[42px] leading-none">solatium</div>
              </div>
              <div className="col-span-2"><Image src={solatium}/></div>
            </div>
          </div>
          <div className="container grid grid-cols-2 mt-44">
            <div className="experience w-[377px]">
              <h3 className="text-[77px]">experience</h3>
              <div className="flex text-[24px]">
                <p>UPWORK</p><span className="ml-auto">21’ - Present</span>
              </div>
              <div className="flex text-[24px]">
                <p>TOK/Digital Agency</p><span className="ml-auto">21’ - Present</span>
              </div>
              <div className="flex text-[24px]">
                <p>BOOST AL</p><span className="ml-auto">21’ - Present</span>
              </div>
              <div className="download mt-14 text-[77px] flex"><h2>resume</h2> <div className="h-9 w-9 ml-[40px]" ><Image src={downloadIcon}/></div></div>
            </div>
            
            <div className="expertise">
              <h3 className="text-[77px]">areas of expertise</h3>
              <div className="text-[24px]">
                <p>Brand Identity</p>
                <p>Art Direction</p>
                <p>Illustrations</p>
                <p>Print Design</p>
                <p>Package Design</p>
                <p>Web Design</p>
              </div>
            </div>
          </div>
      </main>
      <footer className="w-full container">
        <div className="">
          <div className="grid grid-cols-3">
            <div className="col-span-2">
              <div className="flex socials">
                <p>linkedin</p>
                <p>behance</p>
                <p>dribble</p>
                <p>instagram</p>
              </div>
              <div className="flex mail">
                <Link href="deaimeraj99@gmail.com">
                  <a>deaimeraj99@gmail.com</a>
                </Link>
                
              </div>
              <div className="flex"></div>
            </div>
            <div></div>
          </div>
        </div>
      </footer>
    </div>
  );
}
